# .air.toml
[build]
cmd = "go build -o ./tmp/main"
bin = "tmp/main"
full_bin = ""
delay = 1000
exclude_dir = ["tmp", "vendor"]
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_file = []
log = "air.log"
stop_on_error = true
send_interrupt = true

[log]
time = true

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"
