name: OpenGrep Scan
on: [push]

jobs:
  opengrep:
    name: OpenGrep
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install OpenGrep
        run: |
          wget https://github.com/opengrep/opengrep/releases/download/v1.7.0/opengrep_manylinux_x86 -q -O opengrep
          git clone https://github.com/opengrep/opengrep-rules.git
          chmod +x ./opengrep

      - name: Run Semgrep Golang rules
        run: |
          ./opengrep --autofix --error -f ./opengrep-rules/go ./backend || true

      - name: Run Semgrep TS rules
        run: |
          ./opengrep --autofix --error -f ./opengrep-rules/typescript ./frontend || true