name: OpenGrep Scan
on: [push]

jobs:
  opengrep:
    name: OpenGrep
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install OpenGrep
        run: |
          wget https://github.com/opengrep/opengrep/releases/download/v1.7.0/opengrep_manylinux_x86 -q -O opengrep

      - name: Run Semgrep with autofix
        run: |
          git clone https://github.com/opengrep/opengrep-rules.git
          ls -la
          ./opengrep --autofix --error -f ./opengrep-rules ./ || true
